### ISSUE TITLE
Subscriptions example

### ISSUE THREAD

**Issue by haris-begluk** [SimonCropp/GraphQL.EntityFramework#304]
Does this subscription example works?
 Is there some tutorial or doc file, how to test subscriptions inside sample.web project? 
Are you planing to add mutations and subscriptions to this framework?

**Comment by SimonCropp** [comment]
> Does this subscription example works?

AFAIK yes, the subscription integration test passes  https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/src/SampleWeb.Tests/GraphQlControllerTests.cs#L187

> Is there some tutorial or doc file, how to test subscriptions inside sample.web project?

see the above test. as for how to consume a subscription from a GraphQL client, that would depend on the client you are using

>Are you planing to add mutations?

No, since i dont know how this project can add value in that capacity

> Are you planing to add subscriptions to this framework?

As discussed above it already works

**Comment by SimonCropp** [comment]
BTW To be raising issues [you should be a patron](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/licensing-patron-faq.md).
